### ISSUE TITLE
Create Workitem - HTTP 500

### ISSUE THREAD

**Issue by Mershl** [dixudx/rtcclient#88]
Hi dixudx,

Thanks for this project. You already helped me a lot. The last piece that is currently not working for me is creating RTC workitems.

It results in a HTTP 500 error:
```
End of log (HTTP error 500):
DEBUG requests.packages.urllib3.connectionpool: https://rtchost:443 "POST /ccm/oslc/contexts/_qi848CJaEeSy9NmiE0zU4Q/workitems/task HTTP/1.1" 500 184
ERROR client.RTCClient: Failed POST request at <https://rtchost/ccm/oslc/contexts/_qi848CJaEeSy9NmiE0zU4Q/workitems/task> with response: <?xml version="1.0" encoding="UTF-8"?><oslc_cm:error xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/">
<oslc_cm:status>500</oslc_cm:status>
<oslc_cm:message/>
</oslc_cm:error>
```

Trying to access `.../shapes/workitems/task` manually results in the following. I think the OSLC format of the workitem creation is no longer supported. Is this possible?
```
<oslc_cm:error>
<oslc_cm:status>406</oslc_cm:status>
<oslc_cm:message>**OSLC Version '1.0' is not supported.**</oslc_cm:message>
</oslc_cm:error>
```

**Comment by dixudx** [comment]
@Mershl Thanks for using this library.

Probably. Which version is your rtc jazz server. Currently this library has been tested against 5.0.1, 5.0.2 and 6.0.

**Comment by Mershl** [comment]
We have a RTC Jazz 6.0.2 server in use.

**Comment by dixudx** [comment]
@Mershl Currently I don't have such 6.0.2 environment in handy. So would you please help fix it. Thanks.

**Comment by Feva** [comment]
@dixudx As a side point to this and #87 we are running 6.0.3

**Comment by Mershl** [comment]
I've tested some fixes but couldn't successfully create a workitem with 6.0.2 yet. This is the complete log with an unmodified rtcclient: https://gist.github.com/Mershl/1f70e294e107f67238bef45897a7684d

**Comment by dixudx** [comment]
@Mershl Thx. I will take a closer look. Sorry for the inconveniences.

**Comment by Mershl** [comment]
Adding
```
        headers['Accept'] = 'application/rdf+xml'
        headers['OSLC-Core-Version'] = '2.0'
        headers['Content-Type'] = 'text/xml'
```
to L#1119 in [rtcclient/client.py].
Results in two outcomes:
1) HTTP 500, showing a unset expire date in the cookie:
```WASReqURL=""; Expires=Thu, 01-Dec-94 16:00:00 GMT; <...>```

2) HTTP 403, showing missing attribute 'Summary':
```
<rdf:Description rdf:nodeID="A0">
    <oslc:message>'Save Work Item' failed. Preconditions have not been met: The 'Summary' attribute needs to be set (work item &lt;11:42:22&gt;).</oslc:message>
    <oslc:statusCode>403</oslc:statusCode>
    <rdf:type rdf:resource="http://open-services.net/ns/core#Error"/>
  </rdf:Description>
```
Out of 6 consecutive runs. 4 result in expired cookie and 2 in missing attribute.

**Comment by dixudx** [comment]
@Mershl Great! Good progress.

I think 

```
headers['Accept'] = 'application/rdf+xml'
headers['OSLC-Core-Version'] = '2.0'
```

is the key that matters. From your past log, `oslc-core-version` 1.0 is not supported any more in 6.0.3.

We can try to add a new attribute `Summary` when posting a new workitem.

**Comment by Mershl** [comment]
Removing the modification of `Content-Type` results in 
```
<rdf:Description rdf:nodeID="A0">
    <oslc:message>Content type 'application/x-oslc-cm-change-request+xml' is not supported.</oslc:message>
    <oslc:statusCode>415</oslc:statusCode>
    <rdf:type rdf:resource="http://open-services.net/ns/core#Error"/>
  </rdf:Description>
```

**Comment by dixudx** [comment]
@Mershl Thanks for your work. It helps me a lot.

Seems `headers['Accept'] = 'application/rdf+xml'` is also indispensable.

Can you successfully create a new workitem when appending a new attribute `Summary`.

**Comment by Mershl** [comment]
I use the template of a existing work item on the server. The template does not offer a `Summary` attribute (which is weird, as it is required), in which case the Summary argument inside kwargs of [createWorkitem](http://rtcclient.readthedocs.io/en/latest/client.html#rtcclient.client.RTCClient.createWorkitem) is ignored. How would you add an attribute to an existing template?

**Comment by Mershl** [comment]
Based on the spec there is no Summary attribute: [OSLC Spec](http://open-services.net/wiki/change-management/Vocab-V3/).

**Comment by Mershl** [comment]
I think the problem lies within the XML header attributes.
Currently:
```xml
<oslc_cm:ChangeRequest 
    xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/" 
    xmlns:calm="http://jazz.net/xmlns/prod/jazz/calm/1.0/" 
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" 
    xmlns:dc="http://purl.org/dc/terms/" 
    xmlns:oslc_pl="http://open-services.net/ns/pl#" 
    xmlns:rtc_cm="http://jazz.net/xmlns/prod/jazz/rtc/cm/1.0/">
```

**Comment by dixudx** [comment]
@Mershl Actually the `Summary` comes from `dc:title`.

**Comment by Mershl** [comment]
@dixudx Yeah, you're right. But `dc:title` is specified in the POST request.
```xml
<dc:title>OSLC TestTitle</dc:title>
```

**Comment by dixudx** [comment]
Yes, it's quite weird. It works well on my previous environment and has been fully tested.

I wonder whether the oslc version does the trick.

**Comment by dixudx** [comment]
@Mershl Haven't got any clues yet. Will try to find it out.

**Comment by dixudx** [comment]
`403` means the request body is not accepted by the server, either the header or the attributes.

**Comment by dixudx** [comment]
@Mershl @Feva Please try this patch. I've already tested on my env. All works well.

**Special Note**: Please run `pip install -r requirements.txt` to install new package `lxml`.

**Comment by Mershl** [comment]
@dixudx Thanks for the quick patch. 

Due to the etree import from lxml the RTCClient is no longer compatible to Python 2.7.
```
  File "<...>\python_deps\rtcclient\utils.py", line 7, in <module>
    from lxml import etree
ImportError: cannot import name etree
```

I have to support Python 2 due to other dependencies in my project. But I've tried it with 3.5.2 showing:
```
2017-06-02 08:05:57,408 DEBUG urllib3.connectionpool: https://<jazzhost>:443 "GET /ccm/oslc/workitems/305276 HTTP/1.1" 200 17127
2017-06-02 08:05:57,424 DEBUG template.Templater: Successfully remove field [calm:affectsExecutionResult] from the template
Traceback (most recent call last):
  <...>
  File "<...>\python_deps\rtcclient\client.py", line 1048, in createWorkitem
    **kwargs)
  File "<...>\python_deps\rtcclient\client.py", line 1151, in _checkMissingParamsFromWorkitem
    keep=keep)
  File "<...>\python_deps\rtcclient\client.py", line 880, in listFieldsFromWorkitem
    keep=keep)
  File "<...>\python_deps\rtcclient\template.py", line 184, in listFieldsFromWorkitem
    keep=keep)
  File "<...>\python_deps\rtcclient\template.py", line 274, in getTemplate
    self._remove_long_fields(wk_raw_data)
  File "<...>\python_deps\rtcclient\template.py", line 358, in _remove_long_fields
    for key in wk_raw_data.keys():
RuntimeError: OrderedDict mutated during iteration
```

**Comment by dixudx** [comment]
@Mershl I've tested on 2.7.13 and 3.3.6. `lxml` works well.

```
(venv_3.3.6) vagrant@vagrant:~$ python
Python 3.3.6 (default, May 25 2017, 14:23:22) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lxml import etree
>>> exit()
(venv_3.3.6) vagrant@vagrant:~$ workon venv_2.7.13
(venv_2.7.13) vagrant@vagrant:~$ python
Python 2.7.13 (default, May 25 2017, 14:02:15) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from lxml import etree
>>> 
```

**Comment by dixudx** [comment]
@Mershl Yeah, on python 3.5, the runtime error did exist. Fixed in [commit 430f525](https://github.com/dixudx/rtcclient/commit/430f5255c8262c499b96924cccfa776fe84112c1).

**Comment by Mershl** [comment]
I've installed the additional dependencies on Windows (*sign*) for lxml. The work item is now successfully created. Thank you very much for your support @dixudx.

**Comment by Feva** [comment]
@dixudx @Mershl Sorry, i've been away for a few days. After following this and installing the latest development code I can copy a work item from another item. However, I am still unable to create a work item. 

Do you have an example python script showing how you use this please? I know server's etc will be different.

**Comment by dixudx** [comment]
@Feva Please follow [this sample code](https://github.com/dixudx/rtcclient/issues/87#issuecomment-304016831)

**Comment by Feva** [comment]
@dixudx Yes, I have tried that and that does not answer my question I'm afraid. I know the method to call but its the **kwargs that I want an example of. 

I have tried passing all the requested arguments like this:

ownedBy = 'rjw@###.##.##'

or

setting a variable called ownedBy = myclient.getOwnedBy('rjw@###.##.##') and passing that

or 

setting a variable called ownedBy = myclient.getOwnedBy('rjw@###.##.##').url and passing that

for all the arguments that it requires.

I receive either 500, 404 or 409 errors depending upon what I pass.

I am unable to get this to work.

**Comment by dixudx** [comment]
@Feva Would you please show your log and paste to [Github Gist](https://gist.github.com/)?

Actually by setting `ownedBy="someone@here.com"` should work.

**Comment by Feva** [comment]
@dixudx 
This is specifying the values as strings.

https://gist.github.com/Feva/ec54d7266e25b7289b79db66be5696a0

Hope this helps.

**Comment by Feva** [comment]
@dixudx 
This is specifying the values as objects.

https://gist.github.com/Feva/009a2ff15ec4705616b1c528f410d854

Hope this is more help.

**Comment by Feva** [comment]
@dixudx 
Are either of these ways correct?

**Comment by dixudx** [comment]
@Feva [This](https://gist.github.com/Feva/ec54d7266e25b7289b79db66be5696a0) is the correct way.

Would you please help me fetch some data for my reference. Please make sure workitem 65868 has already been assigned to a valid user.

```python
aa=yourclient.getWorkitem(65868)
print(aa.raw_data)
```

**Comment by Feva** [comment]
@dixudx 

Here you go:

https://gist.github.com/Feva/c4cc33a4b02a25bc01f676109cbb1719

**Comment by dixudx** [comment]
@Feva Finally I found the root cause. From [this gist](https://gist.github.com/Feva/c4cc33a4b02a25bc01f676109cbb1719), the attribute value is 

```
(u'rtc_cm:ownedBy', OrderedDict([(u'@rdf:resource', u'http://exelrtc6dev/jts/users/rjw')]))
```

instead of `http://exelrtc6dev/jts/users/rjw%40exel.co.uk`.

That's why **invalid value** is reported when you post a new workitem.

However function `getOwnedBy` will [check the email validation](https://github.com/dixudx/rtcclient/blob/master/rtcclient/client.py#L424-L442). If the email address does not contain `@`, an exception will be raised.

For your usage, I suggest you delete the relative check code in your site-packages.

**Comment by Feva** [comment]
@dixudx 
Thanks for this. Will you be changing this or is this just something that I need for my RTC system?

**Comment by Feva** [comment]
@dixudx 
Thanks for this. Working now. I used:

myclient.getOwnedBy('rjw@exel.co.uk').url.split(urlquote('@'))[0]

So as to leave the standard code alone.

Got template working as well. Notice that palnnedFor was not working but added this in the template like other resources so all fine.

**Comment by dixudx** [comment]
@Feva Glad to see it works on your environment. 

I would like to think out a better way to incorporate these two types (email address and username). For now,  just use that patch. Sorry for the inconveniences.

**Comment by dixudx** [comment]
@krishnavelu Thanks for using this library. Would you mind sharing your full log?

**Comment by krishnavelu** [comment]
Hello dixudx,

Sorry for the late reply. I'll explain my all series of problems one by one for creating a work item.

Version:
Python 			- 3.7
Jazz Server 	- 6.0.2
rtcclient 		- 0.6.0
windows 10

Here is my example [code](https://gist.github.com/krishnavelu/8bbf7a70f0258bb3d509e2d9a0f0649d).

**1. OrderedDict mutated during iteration.**

If I use rtcclient version 0.6.0, I get this [error](https://gist.github.com/krishnavelu/553d323f45a244bd977e3622eed01deb). 
I know this is already bug is already solved in this [commit](https://github.com/dixudx/rtcclient/commit/430f5255c8262c499b96924cccfa776fe84112c1)
So I modified template.py manually as per the commit now its solved.

**2. 'RTCClient' object has no attribute 'getFiledagainst'**

This is the next error after solving 'OrderedDict mutated problem' is [this](https://gist.github.com/krishnavelu/e8e84f14ef8f86aa5bc532af57e09ce9)
This error is also solved in this [commit](https://github.com/dixudx/rtcclient/commit/09168da0f5199b39ec0cbf83b739ebd79f6078bd).
I downloaded the files utils.py and client.py and replaced in following location Lib\site-packages\rtcclient\
But still I couldn't get rid of the 'Cannot replace field [rtc_cm:teamArea]' things. 

After all these I started installing the development version of rtcclient.

**3. TypeError: environment can only contain strings
This is the [procedure](https://gist.github.com/krishnavelu/9102b04ca662b3ba36c89432225b9871) I used to install the development version and it contains the errors too...
I couldn't get rid of this error.

**Comment by dixudx** [comment]
@krishnavelu  Sorry for the late reply.

> Cannot replace field [rtc_cm:teamArea]
Cannot replace field [rtc_cm:foundIn]

> But still I couldn't get rid of the 'Cannot replace field [rtc_cm:teamArea]' things.

 Above are only warnings. Some field settings may not be included in some customized.

The outstanding place is 500 internal error. 

> 2018-09-19 16:51:26,937 ERROR client.RTCClient: Failed POST request at <https://ibmxxx.xxx.xxx.com:9443/ccm/oslc/contexts/_dV4WoEE2Eeim5rPA2MEb6g/workitems/defect> with response: b'<?xml version="1.0" encoding="UTF-8"?><oslc_cm:error xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/">\n<oslc_cm:status>500</oslc_cm:status>\n<oslc_cm:message/>\n</oslc_cm:error>'
2018-09-19 16:51:26,939 INFO client.RTCClient: 500
Traceback (most recent call last):
  File "test.py", line 77, in <module>
    severity = "Normal",
  File "C:\Users\mudalikv\AppData\Local\Programs\Python\Python37\lib\site-packages\rtcclient\client.py", line 1074, in createWorkitem
    return self._createWorkitem(wi_url_post, wi_raw)
  File "C:\Users\mudalikv\AppData\Local\Programs\Python\Python37\lib\site-packages\rtcclient\client.py", line 1122, in _createWorkitem
    data=workitem_raw)
  File "C:\Users\mudalikv\AppData\Local\Programs\Python\Python37\lib\site-packages\rtcclient\utils.py", line 27, in wrapper
    resp = func(*args, **kwargs)
  File "C:\Users\mudalikv\AppData\Local\Programs\Python\Python37\lib\site-packages\rtcclient\base.py", line 123, in post
    response.raise_for_status()
  File "C:\Users\mudalikv\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ibmxxx.xxx.xxx.com:9443/ccm/oslc/contexts/_dV4WoEE2Eeim5rPA2MEb6g/workitems/defect

Above error message does not give us obvious clue. Please help check whether your `defect` need some indispensable settings. It seems some fields are set with empty values.

> <oslc_cm:ChangeRequest xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/" xmlns:calm="http://jazz.net/xmlns/prod/jazz/calm/1.0/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/terms/" xmlns:oslc_pl="http://open-services.net/ns/pl#" xmlns:rtc_cm="http://jazz.net/xmlns/prod/jazz/rtc/cm/1.0/">
        <rtc_cm:archived>false</rtc_cm:archived>
        <rtc_cm:filedAgainst rdf:resource="https://ibmxxx.xxx.xxx.com:9443/ccm/resource/itemOid/com.ibm.team.workitem.Category/_fg8L4Gg5Eeib_4d9Hq06WA"></rtc_cm:filedAgainst>
        <rtc_cm:com.utc.team.apt.attribute.dod>test criteria of acceptance</rtc_cm:com.utc.team.apt.attribute.dod>
        <rtc_cm:com.utc.team.apt.attribute.impacted_api oslc_cm:collref="https://ibmxxx.xxx.xxx.com:9443/ccm/oslc/enumerations/_dV4WoEE2Eeim5rPA2MEb6g/enumerationList$com.utc.enum.impactedkpi"></rtc_cm:com.utc.team.apt.attribute.impacted_api>
        <rtc_cm:com.utc.team.apt.attribute.storyreviewers oslc_cm:collref="https://ibmxxx.xxx.xxx.com:9443/ccm/oslc/workitems/37774/rtc_cm:com.utc.team.apt.attribute.storyreviewers"></rtc_cm:com.utc.team.apt.attribute.storyreviewers>
        <rtc_cm:com.utc.team.apt.attribute.targetrelease rdf:resource="https://ibmxxx.xxx.xxx.com:9443/ccm/resource/itemOid/com.ibm.team.workitem.Deliverable/_-ptuIF0qEeiUlq1De5oDWA"></rtc_cm:com.utc.team.apt.attribute.targetrelease>
        <rtc_cm:correctedEstimate></rtc_cm:correctedEstimate>
        <dc:description>Dummy Story description</dc:description>
        <rtc_cm:due></rtc_cm:due>
        <rtc_cm:estimate></rtc_cm:estimate>
        <rtc_cm:foundIn></rtc_cm:foundIn>
        <rtc_cm:approvals></rtc_cm:approvals>
        <rtc_cm:approvalTasks></rtc_cm:approvalTasks>
        <oslc_cm:priority rdf:resource="https://ibmxxx.xxx.xxx.com:9443/ccm/oslc/enumerations/_dV4WoEE2Eeim5rPA2MEb6g/priority/priority.literal.l01"></oslc_cm:priority>
        <oslc_cm:severity rdf:resource="https://ibmxxx.xxx.xxx.com:9443/ccm/oslc/enumerations/_dV4WoEE2Eeim5rPA2MEb6g/severity/severity.literal.l3"></oslc_cm:severity>
        <dc:subject></dc:subject>
        <rtc_cm:ownedBy rdf:resource="https://ibmxxx.xxx.xxx.com:9443/jts/users/krishna.mudaliar%40carrier.utc.com"></rtc_cm:ownedBy>
        <dc:title>Dummy Story Title</dc:title>
        <rtc_cm:plannedFor rdf:resource="https://ibmxxx.xxx.xxx.com:9443/ccm/oslc/iterations/_fkX6YGg5Eeib_4d9Hq06WA"></rtc_cm:plannedFor>
        <rtc_cm:teamArea></rtc_cm:teamArea>
</oslc_cm:ChangeRequest>

**Comment by krishnavelu** [comment]
Hello 
I forgot to mention, I've checked out development branch. Still I get the same error

> TypeError: environment can only contain strings

I've done this. 

> pip install -r requirements.txt
> Replace files in C:\Users\mudalikv\AppData\Local\Programs\Python\Python37\lib\site-packages\rtcclient.

Now I get a different [error](https://gist.github.com/krishnavelu/10781f8c837196cd5480d3d96850a305)

**Comment by dixudx** [comment]
> Traceback (most recent call last):
  File "test.py", line 77, in <module>
    severity = "Normal",
  File "C:\Users\mudalikv\AppData\Local\Programs\Python\Python37\lib\site-packages\rtcclient\client.py", line 1062, in createWorkitem
    **kwargs)
  File "C:\Users\mudalikv\AppData\Local\Programs\Python\Python37\lib\site-packages\rtcclient\template.py", line 142, in renderFromWorkitem
    return remove_empty_elements(rendered_data)
  File "C:\Users\mudalikv\AppData\Local\Programs\Python\Python37\lib\site-packages\rtcclient\utils.py", line 69, in remove_empty_elements
    root = etree.fromstring(str(docs))
  File "src\lxml\etree.pyx", line 3213, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1872, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

@krishnavelu Encoding error. Could you please verify your post data?

**Comment by dixudx** [comment]
@krishnavelu Please try with this commit 83ecf02aaa17e9201550080b969a6dbb4905ffca.

**Comment by krishnavelu** [comment]
Hello dixudx,

Sorry for the late reply.
I've tried that commit. It give me an error ['str' object has no attribute 'decode'](https://gist.github.com/krishnavelu/43c8a7554f5a03086bb386f34f7a6e54).
I'm using python 3.7.

But changing that function like this worked for me...
I was able to create work items.

`
def remove_empty_elements(docs):
    root = etree.fromstring(bytes(docs, 'utf-8'))
    for element in root.xpath("//*[not(node())]"):
        if "rdf:resource" not in str(etree.tostring(element)):
            element.getparent().remove(element)
 
    return etree.tostring(root)
`

Mostly all of the problems are solved in some commits here and there. But its not yet merged in development.
When will those get merged to development branch and when we can have 0.7.0 eventually...?

**Comment by dixudx** [comment]
> Mostly all of the problems are solved in some commits here and there. But its not yet merged in development.

It is not yet merged in master branch. 

> When will those get merged to development branch and when we can have 0.7.0 eventually...?

I am so glad that this library is so widely used. And thanks for all of you to get this improved.

Please help try latest development branch to verify the newest fix works for you. 0.7.0 is coming soon.

If everything works well, I think 0.7.0 is ready to ship.

**Comment by krishnavelu** [comment]
Hello Dixudx,

(here)[https://gist.github.com/krishnavelu/c8d073f86a4a960a8a5e5ab80d335065] is what I get, when I try to install development version.

**Comment by dixudx** [comment]
@krishnavelu See my comment in your gist.

**Comment by krishnavelu** [comment]
Hello Dixudx,

Even with python3.5 I'm getting the same environment error.

See [here](https://gist.github.com/krishnavelu/a25912ea490f151b0dd9dd2cc265ddcb)
This might be due to the requirement 'pbr!=0.7,<1.0,>=0.6'
Can we not use the latest pbr 4.3.0?

Its just a guess, you may be the right person to answer.

Please note that I'm using windows 10. Which has new type of [environment variable](https://www.ghacks.net/wp-content/uploads/2015/09/windows-10-new-environment-variables-editor.jpg)

**Comment by krishnavelu** [comment]
Hello Dixudx,

One more problem I face now for creating work item is, I'm not able to set a custom attribute.
I've created a custom attribute 'PvcsAcceptedBy' in RTC. And setting through api.
But I'm getting error.

'RTCClient' object has no attribute 'getPvcsAcceptedBy'.

Is custom attributes not supported? If not supported what modification should I do for adding custom attributes.

**Comment by dixudx** [comment]
> This might be due to the requirement 'pbr!=0.7,<1.0,>=0.6'
Can we not use the latest pbr 4.3.0?

@krishnavelu You can give it a try. I don't have an available Windows environment.

> 'RTCClient' object has no attribute 'getPvcsAcceptedBy'.
>
> Is custom attributes not supported? If not supported what modification should I do for adding custom attributes.

Yes, custom attributes are well supported. You can follow [this createWorkitem API](https://rtcclient.readthedocs.io/en/latest/_modules/rtcclient/client.html#RTCClient.createWorkitem). Normally there are two ways to do this,

1. Uses a template. You can try to call [getTemplate](https://rtcclient.readthedocs.io/en/latest/_modules/rtcclient/client.html#RTCClient.getTemplate) to get a template and make your own customizations there.
2. Create a new workitem by copying from another workitem. There is a parameter called `copied_from` in [createWorkitem API](https://rtcclient.readthedocs.io/en/latest/_modules/rtcclient/client.html#RTCClient.createWorkitem)

**Comment by krishnavelu** [comment]
Hello Dixudx,

I guess I'm using the copied_from one. But still I get the error

''RTCClient' object has no attribute 'getPvcsAcceptedBy''

'PvcsAcceptedBy' is the custom attribute.

The work Item gets created but, it doesn't set the value which is passed into createWorkItem. The value of that attribute gets copied from the original WI.

Here is the code I used to create WI. 

`wk = rtc.createWorkitem(item_type = "Story",
                   title = "Dummy Story Title", 
                   description = "Dummy Story description", 
                   projectarea_name = "project area name",
                   copied_from = "41048",
                   filedAgainst = "filedAgainst",
                   plannedFor = "Release 1",
                   ownedBy = ownedBy,
                   priority = "Unassigned",
                   severity = 'Normal',
                   foundIn = 'Coding',
                   PvcsAcceptedBy = "acceptedByPerson"
                   )
`

I really didn't understand the template concept even after reading the document multiple time. Also after getting the template how to modify it for custom attributes?

Could you please give me a example code for creating with custom attribute? What should be passed with **kwargs

**Comment by dixudx** [comment]
> wk = rtc.createWorkitem(item_type = "Story", title = "Dummy Story Title",
description = "Dummy Story description", projectarea_name = "project area name",
copied_from = "41048", filedAgainst = "filedAgainst",
plannedFor = "Release 1", ownedBy = ownedBy,
priority = "Unassigned", severity = 'Normal',
foundIn = 'Coding', PvcsAcceptedBy = "acceptedByPerson"
)

@krishnavelu `PvcsAcceptedBy` is invalid. Here `**kwargs` are for args like `filedAgainst`, `foundIn` and etc, if you does not use a customized template. 

```python
replace_fields = [("rtc_cm:teamArea", "{{ teamArea }}"),
                  ("rtc_cm:ownedBy", "{{ ownedBy }}"),
                  ("rtc_cm:plannedFor", "{{ plannedFor }}"),
                  ("rtc_cm:foundIn", "{{ foundIn }}"),
                  ("oslc_cm:severity", "{{ severity }}"),
                  ("oslc_cm:priority", "{{ priority }}"),
                  ("rtc_cm:filedAgainst", "{{ filedAgainst }}")]
```

You can try to use `getTemplate` to save a template and insert some customized params, like `pvcsAcceptedBy`. Then you can use `pvcsAcceptedBy` when calling  `createWorkitem`.

**Comment by krishnavelu** [comment]
Can I get some example code snippets for modifying the template.
I'm able to do getTemplate. But couldn't get any information about how to modify the custom attributes.

**Comment by dixudx** [comment]
@krishnavelu https://rtcclient.readthedocs.io/en/latest/client.html#rtcclient.client.RTCClient.createWorkitem

```
myclient.createWorkitem("workitem", "title name", description=None, projectarea_id="1234456", template=None, copied_from=23446, keep=False, foundIn="abc", filedAgainst="djlgjal", foundIn="dgag", mycustomized_attr="abc")
```

You just need to pass your template attribute in `createWorkitem`. But you need to make sure `mycustomized_attr` is supported or existed in your RTC environment.

**Comment by jacobbrozenick** [comment]
Any chance the development branch with these changes on it will get committed to master?  I struggled with this exact error for almost 2 weeks before finally finding this thread, works great now!  But I had to pull the development branch (which isn't the version in pypi).

**Comment by gunasekarjo** [comment]
@dixudx Hi I am facing some issue with create work item can u tell me which branch is completely fixed currently I am using development branch which gives me the 409 Client Error: Conflict for url error

**Comment by Narendra0908** [comment]
> @dixudx Thanks for this. Working now. I used:
> 
> myclient.getOwnedBy('[rjw@exel.co.uk](mailto:rjw@exel.co.uk)').url.split(urlquote('@'))[0]
> 
> So as to leave the standard code alone.
> 
> Got template working as well. Notice that palnnedFor was not working but added this in the template like other resources so all fine.
 
Hi @Feva can u please help to create a new workitem using createWorkitem( ) function?

**Comment by Narendra0908** [comment]
@dixudx can we connect some times because still i was not able to create the workitem using rtcclient. i need u r help very badly

**Comment by dixudx** [comment]
@Narendra0908 Feel free to send me an invitation via Google Meet. You could find my email address through the commits. Thanks.

**Comment by Narendra0908** [comment]
@dixudx how to update a work item?

**Comment by Narendra0908** [comment]
[log.txt](https://github.com/dixudx/rtcclient/files/13225072/log.txt)

**Comment by Narendra0908** [comment]
[log.txt](https://github.com/dixudx/rtcclient/files/13225164/log.txt)

**Comment by Narendra0908** [comment]
[log.txt](https://github.com/dixudx/rtcclient/files/13225239/log.txt)

**Comment by Narendra0908** [comment]
[log.txt](https://github.com/dixudx/rtcclient/files/13225291/log.txt)

**Comment by Narendra0908** [comment]
@dixudx when i tried to use the code that u send me via mail the following error occurs: ConnectionError: HTTPSConnectionPool(host='rb-alm-07-p.de.bosch.com', port=9443): Max retries exceeded with url: /jazz/authenticated/identity (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F48FED8760>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by dixudx** [comment]
@Narendra0908 Please use your old way to initialize the RTCClient. And set a proper value for `searchpath`.

**Comment by Narendra0908** [comment]
will do the needful and remaining stuff we can decide in todays meeting scheduled @2

**Comment by dixudx** [comment]
We do have slack https://rtcclient.slack.com/. Welcome to join.

**Comment by Narendra0908** [comment]
I don't have the access for the slack link.

**Comment by dixudx** [comment]
Please use this invitation link https://join.slack.com/t/rtcclient/shared_invite/zt-269osdw4i-fygzMfIeS8s5mDMgNT2DSA

**Comment by Narendra0908** [comment]
still can't access i will try using my personal pc for that since i am using my company network i don 't have access

**Comment by dixudx** [comment]
> will do the needful and remaining stuff we can decide in todays meeting scheduled @2

@Narendra0908 Have you resolved the issues with my template? If so, we could cancel this meeting. Thanks.

**Comment by Narendra0908** [comment]
no the issue is not resolved
we need the meeting
